; PlatformIO Project Configuration for NOISYLESS HeatMap — Node Radar 60GHz
; Target: ESP32-S3
; Framework: ESP-IDF
; Sensor: MinewSemi MS72SF1 via UART 115200 bauds

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.partitions = partitions.csv

build_flags =
    -D CONFIG_FREERTOS_HZ=1000
    -D CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=y
    -D CONFIG_ESP_MAIN_TASK_STACK_SIZE=8192
    -D CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM=10
    -D CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=32
    -D CONFIG_PM_ENABLE=1

lib_deps =
    ; No external deps — all handwritten or ESP-IDF native

board_upload.flash_size = 8MB
