# NOISYLESS Mosquitto config
# Listener 1: plain MQTT (ESP32 firmware, LAN/ingest)
listener 1883
allow_anonymous false
protocol mqtt

# Listener 2: TLS MQTT (future clients externes)
listener 8883
allow_anonymous false
protocol mqtt
cafile /mosquitto/certs/fullchain.pem
certfile /mosquitto/certs/cert.pem
keyfile /mosquitto/certs/privkey.pem
require_certificate false
tls_version tlsv1.2

# Auth
password_file /mosquitto/config/passwd

# Persistence
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest stdout
log_type all
connection_messages true
