; PlatformIO Project Configuration - NOISYLESS v2.0.0
;
; ESP32-S3-MINI-1 (N8, sans PSRAM)
; Modules : BME680/BSEC2 + LD2410 + Analog (lux/mic)

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Hardware S3-MINI-1
board_build.flash_size = 8MB
board_build.psram_type = disabled
board_build.flash_mode = dio
board_build.flash_freq = 40m
board_build.partitions = default.csv

; USB CDC (série sur port USB)
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

; Librairies
lib_deps =
	knolleary/PubSubClient@^2.8.0
	ncmreynolds/ld2410@^0.1.4
	boschsensortec/bsec2@^1.10.2610
	boschsensortec/BME68x Sensor library@^1.3.40408
